#!/usr/bin/with-contenv bash

# workspace dir only (other perms can be done post-launch?)
mkdir -p /config/.config /config/workspace
chown abc:abc /config/.config /config/workspace /config/.config/gcloud/logs /config/.config/gcloud/logs/*
