#!/usr/bin/with-contenv bash

# passwordless sudo 😲🚪⚡💀
echo 'abc ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/00-abc-nopasswd
chmod 0440 /etc/sudoers.d/00-abc-nopasswd

# workspace dir only (other perms can be done post-launch?)
chown abc:abc /config/workspace
